name: The Force

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore Source/SpacePark.sln
    - name: Build
      run: dotnet build --no-restore Source/SpacePark.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Source/SpacePark.sln

  build:

    runs-on: windows-latest  
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore Source/SpacePark.sln
    - name: Build
      run: dotnet build --no-restore Source/SpacePark.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Source/SpacePark.sln